[project]
name = "personal-plan-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Haidarabbas Balospura", email = "haidarabbasbalospura@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.27.0",
    "langchain-core>=1.6.6",
    "langchain-google-genai>=4.4.0",
    "langchain-openrouter>=0.2.9",
    "python-dotenv>=1.2.4",
    "requests>=2.34.2",
    "streamlit>=1.64.0",
]
